import LayoutClient from '@/components/layout/layout'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
// const geist = GeistSans({variable: '--font-geist'})
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: 'logo.svg',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={GeistSans.className}>
				<LayoutClient>{children}</LayoutClient>
			</body>
		</html>
	)
}
